### ISSUE TITLE
Error happened while attempting to execute 'mvn clean package' in Go CD

### ISSUE THREAD

**Issue by julwanik** [dtsato/devops-in-practice-workshop#4]
0

I have setup a pipeline as described in step11. with task mvn clean package in Go CD. All steps are followed correctly, still When I trigger the pipeline, the job fails:

[go] Task: mvn clean package took: 0.14s Error happened while attempting to execute 'mvn clean package'. Please make sure [mvn] can be executed on this agent.

[Debug Information] Environment variable PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-11-openjdk/bin

I have tried all solutions provided on the below post-but nothing works Can't execute "mvn clean package" task in GO CD

**Comment by dtsato** [comment]
Instead of `mvn clean package`, please use the Maven wrapper `./mvnw clean package` for the command. The wrapper doesn't expect Maven to be installed in the agent, but instead will download the correct version if not found.

**Comment by julwanik** [comment]
Hi Daniel. I did try the above but to no success
also I searched on below solutions on SO but they are also not working for me-
https://stackoverflow.com/questions/66196375/error-happened-while-attempting-to-execute-mvn-clean-package-in-go-cd

**Comment by julwanik** [comment]
Is there any tutorial video where this workshop instructions are recorded?
